trigger:
- main  # Change this to the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and push an image to container registry'
  inputs:
    containerRegistry: 'Azure Container Registry'  # Replace this with your Azure Container Registry connection name
    repository: 'azure-demo-image'  # Replace this with the name you want to give your Docker image
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'  # Assuming your Dockerfile is located in the root directory of your repository
    tags: |
      latest
