# Azure Pipelines YAML file for Maven-based Java project

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    version: '17'

- script: |
    mvn clean install
  displayName: 'Build Java project with Maven'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    artifactName: 'java-project-artifact'
    publishLocation: 'Container'
